#!/bin/bash

set -e

dot="$(cd "$(dirname "$0")"; pwd)"
policy_output_path="$dot/policy"
which policy-tool
sha256sum `which policy-tool`
policy-tool -d -t $dot/../policies/entities -m $dot/../policies -o $policy_output_path osv.frtos.main.none

cp -r soc_cfg policy
